project:
  type: book
  output-dir: docs

book:
  title: "Data Science con Python e R"
  subtitle: "Esercitazioni Pratiche"
  author: "Corrado Caudek"
  date: "last-modified"
  search: true
  repo-url: https://github.com/ccaudek/psicometria-esercizi/
  repo-actions: []
  site-url: https://ccaudek.github.io/psicometria-esercizi/intro.html
  page-footer:
    left: |
      Data Science con Python e R è stato scritto da Corrado Caudek.
    right: |
      Questo libro è stato realizzato con <a href="https://quarto.org/">Quarto</a>.
  sidebar:
    collapse-level: 1
    pinned: true

  chapters:
    - index.qmd
    - prefazione.qmd

    - part: "Python"
      chapters:
        - chapters/python/01_python.qmd

    - part: "EDA"
      chapters:
        - chapters/eda/01_eda.qmd

    - part: "Probabilità"
      chapters:
        - chapters/probability/01_probability.qmd

bibliography: ./references.bib

lang: it

format:
  html:
    toc: true
    toc-depth: 5
    format-options:
      html:
        table-class: table table-striped table-hover table-bordered
    smooth-scroll: true
    theme: cosmo
    highlight-style: github
    code-link: true
    code-tools: true
    include-in-header: _includes/solutions.html
    author-meta: "Corrado Caudek"
    callout-appearance: simple

editor: visual

website:
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-TP2WLBPMS6"
    anonymize-ip: true
